name: CA
on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout cod
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Set up QEMU
        if: success()
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        if: success()
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: tanyibai/cicd_workshop/:${{ github.sha}}